### ISSUE TITLE
met issue when run python inference.py

### ISSUE THREAD

**Issue by HulkMaker** [AlexanderParkin/ChaLearn_liveness_challenge#3]
Traceback (most recent call last):
  File "inference.py", line 7, in <module>
    from trainer import Model
  File "/home/qing/face/visionlabs/trainer.py", line 9, in <module>
    import models, datasets, utils
  File "/home/qing/face/visionlabs/models/__init__.py", line 1, in <module>
    from .init_model import init_loss, get_model
  File "/home/qing/face/visionlabs/models/init_model.py", line 1, in <module>
    from .architectures import MobileNetV2
  File "/home/qing/face/visionlabs/models/architectures/__init__.py", line 1, in <module>
    from .mobilenetv2b import MobileNetV2
ModuleNotFoundError: No module named 'models.architectures.mobilenetv2b'

**Comment by HulkMaker** [comment]
short this file "models.architectures.mobilenetv2b"

**Comment by lauhsu** [comment]
@muyiguangda  Have you found the file "models.architectures.mobilenetv2b"?

**Comment by HulkMaker** [comment]
still not. No one reply.

**Comment by chelus** [comment]
It seems that this issue has been solved here: https://github.com/AlexanderParkin/ChaLearn_liveness_challenge/issues/9#issuecomment-577484942

**Comment by xiaohemiao123** [comment]
> still not. No one reply.

兄嘚，最后有没有运行成功？
